theme: jekyll-theme-cayman

<html>
<title>
Privates
</title>
<body>

<basefont face = "arial" size = "2",color = "red">
<p style = "text-align:center;"><font size = "+2" color = "blue">You are using VPN to access the site, This is against our rules,remove VPN and try again</font></p>
<p style = "text-align:center;"><font size= "+1" color = "red"><a href ="b.html">Click here to refresh and get into heaven</a></font></p>

</body>
</html>
